# Generated by Django 6.1 on 2026-08-14 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardianship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(default='parent', max_length=32)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('guardian', 'Guardian'), ('student', 'Student')], max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('grade', models.CharField(max_length=8)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('guardians', models.ManyToManyField(related_name='wards', through='passport.Guardianship', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('record_count', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='passport.student')),
            ],
        ),
        migrations.AddField(
            model_name='guardianship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passport.student'),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('grade', models.CharField(blank=True, max_length=8)),
                ('period', models.CharField(blank=True, max_length=16)),
                ('teachers', models.ManyToManyField(related_name='classrooms', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='classrooms', to='passport.student')),
            ],
            options={
                'ordering': ['period', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='guardianship',
            unique_together={('guardian', 'student')},
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sis', 'Student information system'), ('assessment', 'Assessment'), ('attendance', 'Attendance'), ('behavior', 'Behavior'), ('document', 'Document (IEP, 504, report card)'), ('ai_tutor', 'AI tutor interaction'), ('observation', 'Teacher observation'), ('parent_input', 'Guardian input'), ('student_input', 'Student input'), ('question', 'Asked question')], max_length=24)),
                ('kind', models.CharField(blank=True, max_length=64)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='passport.student')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'source', 'date'], name='passport_st_student_80ef50_idx')],
            },
        ),
    ]
