# Generated by Django 6.1 on 2026-08-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='source',
            field=models.CharField(choices=[('sis', 'Student information system'), ('assessment', 'Assessment'), ('attendance', 'Attendance'), ('behavior', 'Behavior'), ('document', 'Document (IEP, 504, report card)'), ('ai_tutor', 'AI tutor interaction'), ('engagement', 'Engagement sample'), ('observation', 'Teacher observation'), ('parent_input', 'Guardian input'), ('student_input', 'Student input'), ('question', 'Asked question')], max_length=24),
        ),
    ]
