# Generated by Django 6.1 on 2026-08-15 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0002_alter_studentrecord_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='source',
            field=models.CharField(choices=[('sis', 'Student information system'), ('assessment', 'Assessment'), ('attendance', 'Attendance'), ('behavior', 'Behavior'), ('document', 'Document (IEP, 504, report card)'), ('ai_tutor', 'AI tutor interaction'), ('engagement', 'Engagement sample'), ('observation', 'Teacher observation'), ('parent_input', 'Guardian input'), ('student_input', 'Student input'), ('question', 'Asked question'), ('app_integration', 'Learning-app activity (practice or reading session)')], max_length=24),
        ),
        migrations.CreateModel(
            name='DailyDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('summary', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('record_count', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='passport.student')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
