# Generated by Django 6.1 on 2026-08-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0003_alter_studentrecord_source_dailydigest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='source',
            field=models.CharField(choices=[('sis', 'Student information system'), ('assessment', 'Assessment'), ('attendance', 'Attendance'), ('behavior', 'Behavior'), ('document', 'Document (IEP, 504, report card)'), ('ai_tutor', 'AI tutor interaction'), ('cognitive_analysis', 'AI use / cognitive analysis'), ('engagement', 'Engagement sample'), ('observation', 'Teacher observation'), ('parent_input', 'Guardian input'), ('student_input', 'Student input'), ('question', 'Asked question'), ('app_integration', 'Learning-app activity (practice or reading session)')], max_length=24),
        ),
    ]
