# Generated by Django 6.1 on 2026-08-15 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0004_clear_digests_for_renamed_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('summary', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('record_count', models.IntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='passport.classroom')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('classroom', 'date')},
            },
        ),
    ]
